/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        ink:           '#111111',
        brick:         '#C0392B',
        'brick-dark':  '#A93226',
        'brick-light': '#FCECEA',
        mustard:       '#D4A017',
        chalk:         '#F8F6F1',
        'chalk-dark':  '#EFEDE8',
        slate:         '#71717A',
        border:        '#E4E4E7',
        white:         '#FFFFFF',
        primary: {
          DEFAULT: '#C0392B',
          hover:   '#A93226',
        },
        secondary:  '#111111',
        background: '#F8F6F1',
        surface:    '#FFFFFF',
        text: {
          DEFAULT: '#111111',
          muted:   '#71717A',
        },
      },
      fontFamily: {
        heading: ['"Plus Jakarta Sans"', 'sans-serif'],
        display: ['"Plus Jakarta Sans"', 'sans-serif'],
        body:    ['Inter', 'sans-serif'],
        mono:    ['"JetBrains Mono"', 'monospace'],
      },
      borderRadius: {
        sm: '6px', md: '10px', lg: '16px', xl: '24px',
      },
      boxShadow: {
        xs:      '0 1px 4px rgba(17,17,17,0.06)',
        sm:      '0 2px 12px rgba(17,17,17,0.08)',
        md:      '0 8px 28px rgba(17,17,17,0.10)',
        lg:      '0 20px 60px rgba(17,17,17,0.14)',
        card:    '0 2px 12px rgba(17,17,17,0.08)',
        dropdown:'0 8px 28px rgba(17,17,17,0.10)',
        btn:     '0 4px 14px rgba(192,57,43,0.30)',
        glow:    '0 0 0 3px rgba(192,57,43,0.15)',
      },
      maxWidth: { container: '1180px' },
      animation: {
        'fade-up':      'fadeUp 0.55s cubic-bezier(0.16,1,0.3,1) both',
        'fade-in':      'fadeIn 0.4s ease both',
        'fade-in-up':   'fadeUp 0.55s cubic-bezier(0.16,1,0.3,1) both',
        'scale-in':     'scaleIn 0.2s cubic-bezier(0.16,1,0.3,1) both',
        'slide-down':   'slideDown 0.2s ease forwards',
        'pulse-dot':    'pulseDot 1.5s ease-in-out infinite',
        'float-1':      'float 4s ease-in-out infinite',
        'float-2':      'float 4s ease-in-out infinite 0.7s',
        'float-3':      'float 4s ease-in-out infinite 1.4s',
        'bounce-slow':  'bounceSlow 3s ease-in-out infinite',
        'spin-slow':    'spin 8s linear infinite',
      },
      keyframes: {
        fadeUp:     { from: { opacity: '0', transform: 'translateY(24px)' }, to: { opacity: '1', transform: 'none' } },
        fadeIn:     { from: { opacity: '0' }, to: { opacity: '1' } },
        scaleIn:    { from: { opacity: '0', transform: 'scale(0.94) translateY(-8px)' }, to: { opacity: '1', transform: 'scale(1) translateY(0)' } },
        slideDown:  { from: { opacity: '0', transform: 'translateY(-8px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        pulseDot:   { '0%,100%': { opacity: '1', transform: 'scale(1)' }, '50%': { opacity: '0.5', transform: 'scale(1.4)' } },
        float:      { '0%,100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-10px)' } },
        bounceSlow: { '0%,100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-10px)' } },
      },
    },
  },
  plugins: [],
};